language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - coverage run --source=crudbuilder runtests.py
env:
  matrix:
   - DJANGO="1.10.8"
   - DJANGO="1.11.8"
   - DJANGO="2.0"

matrix:
  exclude:
    # Django 2.0 no longer support python2
    - python: "2.7"
      env: DJANGO="2.0"

install:
  - pip install -q Django==$DJANGO
  - python setup.py -q install
  - pip install coveralls
after_success:
  coveralls