# Generated by Django 2.1.4 on 2019-01-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
