# Generated by Django 2.1.4 on 2019-01-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerauth', '0002_auto_20190127_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='address',
        ),
    ]
