# Generated by Django 2.1.4 on 2019-01-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerauth', '0004_auto_20190127_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
