# Generated by Django 2.1.4 on 2019-01-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_owner', models.CharField(max_length=20)),
                ('c_reg_no', models.IntegerField()),
                ('c_adress', models.TextField()),
                ('c_phone', models.IntegerField()),
                ('c_email', models.EmailField(max_length=254)),
                ('c_description', models.TextField()),
                ('c_created_date', models.TimeField()),
                ('c_updated_date', models.TimeField()),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
            ],
        ),
    ]
