# Generated by Django 2.1.4 on 2019-01-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='min_length',
            field=models.IntegerField(default='8', editable=False, max_length=7),
        ),
    ]
