# Generated by Django 2.1.4 on 2019-01-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_vendors_min_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='c_logo',
            field=models.ImageField(default='NULL', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='c_url',
            field=models.URLField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='vendors',
            name='image',
            field=models.ImageField(default='NULL', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='c_adress',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='c_created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='c_description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='c_email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='c_updated_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
