# Generated by Django 2.1.4 on 2019-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20190120_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='c_adress',
            field=models.TextField(max_length=200),
        ),
    ]
