# Generated by Django 2.1.4 on 2019-01-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20190120_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='address',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='vendors',
            name='mobileNo',
            field=models.IntegerField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='email',
            field=models.EmailField(default='NULL', max_length=30),
        ),
    ]
