# Generated by Django 2.1.4 on 2019-01-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20190120_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='mobileNo',
            field=models.IntegerField(),
        ),
    ]
