# Generated by Django 2.1.4 on 2019-01-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_auto_20190120_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
