# Generated by Django 2.1.4 on 2019-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20190120_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='address',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
