# Generated by Django 2.1.4 on 2019-01-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_remove_vendors_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='addres',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
