# Generated by Django 2.1.4 on 2019-01-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_vendors_addres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='addres',
            field=models.CharField(max_length=200),
        ),
    ]
