# Generated by Django 2.1.4 on 2019-01-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_auto_20190120_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
