# Generated by Django 2.1.4 on 2019-01-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_remove_vendors_addres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='mobileNo',
        ),
    ]
