# Generated by Django 2.1.4 on 2019-01-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_remove_vendors_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='c_adress',
            field=models.TextField(max_length=20),
        ),
    ]
