# Generated by Django 2.1.4 on 2019-01-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pub_ate',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fkey',
            new_name='user',
        ),
    ]
